apiVersion: v1
data:
  POSTGRES_DB: mwdb
  POSTGRES_PASSWORD: 20a8e52e7c047648896d801a69a5025f7ccc
  POSTGRES_USER: mwdb
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: postgres-postgres-vars-env
  name: postgres-vars-env
