apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  clusterIP: None
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
root@aws-cli:~/aws-proj/learn-terraform-provision-eks-cluster/mwdb-core# cat postgres.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:9
        ports:
        - containerPort: 5432
#          name: postgres
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: mwdb-postgres
#        envFrom:
#          - configMapRef:
#              name: postgres-configmap
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_DB
              name: postgres-vars-env
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PASSWORD
              name: postgres-vars-env
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_USER
              name: postgres-vars-env
      restartPolicy: Always
      volumes:
        - name: mwdb-postgres
          emptyDir: {}
